version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: pg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5532:5532'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-pg
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '50601:80'
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
